//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.17 at 02:55:47 PM ICT 
//


package com.demo.orderJB;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="orderdetail" type="{http://xml.netbeans.org/schema/orders}OrderDetail" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="total" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cutomerName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="customerPhone" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="delAddress" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="delState" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="delCity" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "orderdetail"
})
@XmlRootElement(name = "order")
public class Order {

    @XmlElement(required = true)
    protected List<OrderDetail> orderdetail;
    @XmlAttribute(name = "total")
    protected BigInteger total;
    @XmlAttribute(name = "date")
    protected String date;
    @XmlAttribute(name = "cutomerName")
    protected String cutomerName;
    @XmlAttribute(name = "customerPhone")
    protected BigInteger customerPhone;
    @XmlAttribute(name = "delAddress")
    protected String delAddress;
    @XmlAttribute(name = "delState")
    protected String delState;
    @XmlAttribute(name = "delCity")
    protected String delCity;

    /**
     * Gets the value of the orderdetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderdetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderdetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderDetail }
     * 
     * 
     */
    public List<OrderDetail> getOrderdetail() {
        if (orderdetail == null) {
            orderdetail = new ArrayList<OrderDetail>();
        }
        return this.orderdetail;
    }

    /**
     * Gets the value of the total property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotal(BigInteger value) {
        this.total = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the cutomerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCutomerName() {
        return cutomerName;
    }

    /**
     * Sets the value of the cutomerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCutomerName(String value) {
        this.cutomerName = value;
    }

    /**
     * Gets the value of the customerPhone property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCustomerPhone() {
        return customerPhone;
    }

    /**
     * Sets the value of the customerPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCustomerPhone(BigInteger value) {
        this.customerPhone = value;
    }

    /**
     * Gets the value of the delAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelAddress() {
        return delAddress;
    }

    /**
     * Sets the value of the delAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelAddress(String value) {
        this.delAddress = value;
    }

    /**
     * Gets the value of the delState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelState() {
        return delState;
    }

    /**
     * Sets the value of the delState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelState(String value) {
        this.delState = value;
    }

    /**
     * Gets the value of the delCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelCity() {
        return delCity;
    }

    /**
     * Sets the value of the delCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelCity(String value) {
        this.delCity = value;
    }

}
